### ISSUE TITLE
title没有正常显示

### ISSUE THREAD

**Issue by SageJustus** [sunburst89757/react-ts-admin#1]
子组件的title被父组件的title覆盖了，首次进入`http://localhost:3000/purchaseManage/supplierManage`时，`title`应为`供应商管理`，实际是`采购管理`

![屏幕截图 2022-06-09 212420](https://user-images.githubusercontent.com/39724295/172857888-53ba16e5-732a-436f-83ac-458d4ed2cfce.png)

**Comment by sunburst89757** [comment]
已修复
